import type { Metadata } from "next";
import "./globals.css";

import { Noto_Sans_JP } from "next/font/google";
const notoSansJp = Noto_Sans_JP({
  weight: ["400", "700"],
  display: "swap",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ja" className={notoSansJp.className}>
      <body>{children}</body>
    </html>
  );
}
